package modelo;
// Generated 22 mar 2023 9:55:20 by Hibernate Tools 4.3.6.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "Products", catalog = "salesdb")
public class Products implements java.io.Serializable {

	private Integer productId;
	private String name;
	private BigDecimal price;
	private Sales sales;
	private Customers customers;

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn(name="idCostumer", nullable=false)
	public Customers getCustomers() {
		return customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	public Products() {
	}

	public Products(String name) {
		this.name = name;
	}

	@ManyToOne (fetch = FetchType.LAZY)
	@JoinColumn(name="idSales", nullable=false)
	public Sales getSales() {
		return sales;
	}

	public void setSales(Sales sales) {
		this.sales = sales;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ProductID", unique = true, nullable = false)
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Price", scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}



}
