package modelo;
// Generated 22 mar 2023 9:55:20 by Hibernate Tools 4.3.6.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

/**
 * Sales generated by hbm2java
 */
@Entity
@Table(name = "Sales", catalog = "salesdb")
public class Sales implements java.io.Serializable {

	private Integer salesId;
	private Customers customers;
	private Employees employees;
	private Set<Products> products=new HashSet<Products>(0);
	private int quantity;

	public Sales() {
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "SalesID", unique = true, nullable = false)
	public Integer getSalesId() {
		return this.salesId;
	}

	public void setSalesId(Integer salesId) {
		this.salesId = salesId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sales")
	public Set<Products> getProducts() {
		return products;
	}

	public void setProducts(Set<Products> products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerID", nullable = false)
	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SalesPersonID", nullable = false)
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}



	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
